# Wirepas Oy

version: '2'
services:
    wm-broker-bridge:
        container_name: wm-broker-bridge
        image: wirepas/mosquitto-bridge
        build: .

        restart: always

        ports:
            - 1883:1883
            - 8883:8883

        logging:
            driver: json-file
            options:
                max-size: "1M"

        volumes:
          - ./mosquitto.conf:/etc/mosquitto/conf.d/wirepas.conf
