# Wirepas Oy

version: '2'
services:
    node_red:
        image: wirepas/node-red:latest
        build: .

        restart: always

        ports:
            - 1880:1880

        logging:
            driver: journald
