# Copyright 2019 Wirepas Ltd

version: '2'
services:
    node_red:
        image: wirepas/node-red:latest
        build: .

        restart: always

        ports:
            - 1880:1880

        logging:
            driver: json-file
            options:
                max-size: "1M"
