# Wirepas Oy

version: '2'
services:
    wm-broker:
        container_name: wm-broker
        image: wirepas/mosquitto
        build: .

        restart: always

        environment:
            - MQTT_USERNAME=mqttuser
            - MQTT_PASSWORD=pleasesetthispassword

        ports:
            - 1883:1883
            - 8883:8883

        logging:
            driver: json-file
            options:
                max-size: "1M"
