# Copyright 2019 Wirepas Ltd

version: '2'
services:
    wm-broker:
        container_name: wm-broker
        image: wirepas/mosquitto
        build: .

        restart: always

        # Both the default parameters:
        # - MQTT_USERNAME
        # - MQTT_PASSWORD
        # or the wirepas keys will be taken into use.
        # The image defaults take precedence.
        # To use this composition as is, make sure to set
        # and export the WM_SERVICES_(...) parameters
        environment:
            - MQTT_USERNAME=${WM_SERVICES_MQTT_USERNAME}
            - MQTT_PASSWORD=${WM_SERVICES_MQTT_PASSWORD}

        ports:
            - 1883:1883
            - 8883:8883

        logging:
            driver: json-file
            options:
                max-size: "1M"
