# Wirepas Oy

version: '2'
services:
    wm-broker:
        container_name: wm-broker
        image: wirepas/mosquitto
        build: .

        restart: always

        ports:
            - 1883:1883
            - 8883:8883

        logging:
            driver: journald
