# Wirepas Oy
# To set the timezone of your server, other than utc.
# Add the following key in the db environment with your desired TZ
#
# - TZ=Europe/Helsinki
#

version: '2'
services:
    wm-mysql:
        container_name: wm-mysql
        image: wirepas/mysql:latest
        build: .

        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=mydatabase
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=mypwd


        restart: always

        # storage
        volumes:
            - storage:/var/lib/mysql/

        # network
        ports:
            - 3306:3306

        logging:
            driver: json-file
            options:
                max-size: "1M"

# persistent data location
volumes:
    storage: {}
