# Copyright 2019 Wirepas Ltd
#
# This docker compose is an example and should not be used for production
# environments. This is solely for demonstration and evaluation purposes.
#
# By default the backend-client will connect to the local broker defined in
# the mqtt-broker service. If you want it to decode packets and obtain
# data within kibana, please route your gateway traffic towards your
# localhost at port 1883.
#
#
# If you want to connect to an external broker, please review the following
# settings (under the backend-client service enntry) carefully:
#
#            "--mqtt_hostname=< IP or hostname of your MQTT broker >",
#            "--mqtt_username=< username >",
#            "--mqtt_password=< password >",
#            "--mqtt_force_unsecure",
#
# The force unsecure must be added when you are trying to connect to a
# local broker on port 1883. Please remove the flag if you are trying
# to connect against a remote/local secure broker.
#
# If you want to connect against the mqtt-broker service, the command
# must be changed to
#

version: '2'
services:

    # An example mqtt broker
    mqtt-broker:
        container_name: mqtt-broker
        image: wirepas/mosquitto:latest
        restart: always
        networks:
            - cookbook_visualization
        ports:
            - 1883:1883
            - 8883:8883
        environment:
            - WM_SERVICES_MQTT_USERNAME=mqttuser
            - WM_SERVICES_MQTT_PASSWORD=mqttpassword
        logging:
            driver: json-file
            options:
                max-size: "1M"

    node_red:
        image: wirepas/node-red:latest
        restart: always
        ports:
            - 1880:1880
        logging:
            driver: json-file
            options:
                max-size: "1M"

    # Handles the decoding of network packets
    backend-client:
        container_name: backend-client
        image: wirepas/backend-client:v1.2.0
        restart: always
        networks:
            - cookbook_visualization

        environment:
          - WM_DEBUG_LEVEL=info
          - PYTHONUNBUFFERED=true

        user: wirepas
        #working_dir: /home/wirepas/

        command: [
            "python",
            "/home/wirepas/.local/wirepas_backend_client-extras/examples/mqtt_viewer.py",
            "--mqtt_hostname=mqtt-broker",
            "--mqtt_username=mqttuser",
            "--mqtt_password=mqttpassword",
            "--mqtt_port=1883",
            "--mqtt_force_unsecure",
            "--fluentd_hostname=fluentd",
            "--fluentd_record=app",
            "--fluentd_tag=ruuvi"
        ]

        logging:
            driver: json-file
            options:
                max-size: "1M"

    # Fluentd - logs events into elastic search
    fluentd:
        container_name: fluentd
        image: wirepas/fluentd:latest
        restart: always
        networks:
            - cookbook_visualization
        logging:
            driver: json-file
            options:
                max-size: "1M"

    # ELK stack
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1

        environment:
          - discovery.type=single-node
          - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

        restart: always

        volumes:
            - esdata:/usr/share/elasticsearch/data

        networks:
            - cookbook_visualization


        logging:
            driver: json-file
            options:
                max-size: "1M"

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.1.1
        environment:
            - elasticsearch.hosts=["http://elasticsearch:9200"]
        restart: always
        ports:
            - 5601:5601
        networks:
            - cookbook_visualization
        logging:
            driver: json-file
            options:
                max-size: "1M"

volumes:
  esdata:
    driver: local

networks:
  cookbook_visualization:
